melis_platform_framework_symfony_demo_tool_logic:
    table:
        album_table:
            target: '#tableSymfonyDemoTool'
            ajaxUrl: '/melis/album-list'
            dataFunction: ''
            ajaxCallback: ''
            filters:
                left:
                    show: l
                center:
                    search: f
                right:
                    refresh: '<a class="btn btn-default melis-refreshTable" data-toggle="tab" aria-expanded="true" title="Refresh"><i class="fa fa-refresh"></i></a>'
            columns:
                albId:
                    text: 'Id'
                    css:
                        width: '5%'
                        padding-right: 0
                    sortable: false
                albName:
                    text: 'Name'
                    css:
                        width: '50%'
                        padding-right: 0
                    sortable: false
                albSongNum:
                    text: 'Song number'
                    css:
                        width: '25%'
                        padding-right: 0
                    sortable: false
                albDate:
                    text: 'Date'
                    css:
                        width: '25%'
                        padding-right: 0
                    sortable: false
            searchables: ['alb_name', 'alb_song_num']
            actionButtons:
                edit: '<button class="btn btn-success btn_update" title="Edit"><i class="fa fa-pencil"></i></button>'
                delete: '<a class="btn btn-danger btn_delete" title="Delete"><i class="fa fa-times"> </i></a>'
