#in this route, we added a prefix /melis
#because we wan't our route to access
#data in the Melis Platform Back office
#if you didn't put a /melis in your route
#then it will get the data from the front (site)

list_route:
  path: /melis/symfony-list
  controller: MelisPlatformFrameworkSymfonyDemoToolLogic\Controller\AlbumController::getAlbumTool

album_list:
  path: /melis/album-list
  controller: MelisPlatformFrameworkSymfonyDemoToolLogic\Controller\AlbumController::getAlbumList

#Get album by id
create_album_form:
  path: /melis/create-form/{id}
  controller : MelisPlatformFrameworkSymfonyDemoToolLogic\Controller\AlbumController::createAlbumForm
  methods: GET|HEAD

#Save
save_album:
  path: /melis/save-album/{id}
  controller: MelisPlatformFrameworkSymfonyDemoToolLogic\Controller\AlbumController::saveAlbum
  defaults:   { id: 0 }
  methods: POST

#Delete
delete_album:
  path: /melis/delete-album
  controller: MelisPlatformFrameworkSymfonyDemoToolLogic\Controller\AlbumController::deleteAlbum
  methods: POST

#we used the same function in the controller
#to ge the data for the plugin.
#This time we didn't put a /melis on our route
#since we need to access it in the front
plugin_route:
  path: /symfony-plugin
  controller: MelisPlatformFrameworkSymfonyDemoToolLogic\Controller\AlbumController::getAlbumPlugin