<?php

namespace MelisPlatformFrameworkSymfonyDemoToolLogic\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder('melis_platform_framework_symfony_demo_tool_logic');
        $treeBuilder->getRootNode()
            ->children()
                ->arrayNode('table')
                    ->children()
                        ->arrayNode('album_table')
                            ->children()
                                ->variableNode('target')->defaultValue('#tableSymfonyDemoTool')->end()
                                ->variableNode('ajaxUrl')->defaultValue('/melis/album-list')->end()
                                ->variableNode('dataFunction')->defaultNull()->end()
                                ->variableNode('ajaxCallback')->defaultNull()->end()
                                ->arrayNode('filters')
                                    ->children()
                                        ->arrayNode('left')
                                            ->children()
                                                ->variableNode('show')
                                                    ->defaultValue('l')
                                                ->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('center')
                                            ->children()
                                                ->variableNode('search')
                                                    ->defaultValue('f')
                                                ->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('right')
                                            ->children()
                                                ->variableNode('refresh')
                                                    ->defaultValue('<a class="btn btn-default">Refresh</a>')
                                                ->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('columns')
                                    ->children()
                                        ->arrayNode('albId')
                                            ->children()
                                                ->variableNode('text')->defaultValue('Id')->end()
                                                ->arrayNode('css')
                                                    ->children()
                                                        ->variableNode('width')->defaultValue('5%')->end()
                                                        ->variableNode('padding_right')->defaultValue(0)->end()
                                                    ->end()
                                                ->end()
                                                ->variableNode('sortable')->defaultFalse()->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('albName')
                                            ->children()
                                                ->variableNode('text')->defaultValue('Name')->end()
                                                ->arrayNode('css')
                                                    ->children()
                                                        ->variableNode('width')->defaultValue('5%')->end()
                                                        ->variableNode('padding_right')->defaultValue(0)->end()
                                                    ->end()
                                                ->end()
                                                ->variableNode('sortable')->defaultFalse()->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('albSongNum')
                                            ->children()
                                                ->variableNode('text')->defaultValue('Song number')->end()
                                                ->arrayNode('css')
                                                    ->children()
                                                        ->variableNode('width')->defaultValue('5%')->end()
                                                        ->variableNode('padding_right')->defaultValue(0)->end()
                                                    ->end()
                                                ->end()
                                                ->variableNode('sortable')->defaultFalse()->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('albDate')
                                            ->children()
                                                ->variableNode('text')->defaultValue('Date')->end()
                                                ->arrayNode('css')
                                                    ->children()
                                                        ->variableNode('width')->defaultValue('5%')->end()
                                                        ->variableNode('padding_right')->defaultValue(0)->end()
                                                    ->end()
                                                ->end()
                                                ->variableNode('sortable')->defaultFalse()->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                                ->variableNode('searchables')->defaultValue([])->end()
                                ->arrayNode('actionButtons')
                                    ->children()
                                        ->variableNode('edit')
                                            ->defaultValue('<a class="btn btn-default">Edit</a>')
                                        ->end()
                                        ->variableNode('delete')
                                            ->defaultValue('<a class="btn btn-danger">Delete</a>')
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();
        return $treeBuilder;
    }
}